### ISSUE TITLE
liberation server restart script

### ISSUE THREAD

**Issue by madpat3** [k4s0/Personal_Website#1]
hello,
i don't know how to contact you otherways, so i do it this way.
i saw your server restart script in the liberation mission for arma 3.

i have two questions. does the mission auto-restart, if i put in the command "#restart" and does the server auto-restart, if i put in the command "#restartserver"?

and can this script be modified, to start HCs along with the server?

**Comment by k4s0** [comment]
hi @madpat3  if you run the arma3server under linux you can only use #restart(restart the mission not the arma3server process) , otherwise if you running it under windows you can use #restartserver(this restart the arma3server process and if you use the correct parameters at the start you can launch the HC properly ) .

**Comment by madpat3** [comment]
o.k. i think we have a linux server, but never the less, it doesn't work.
we get the messages like 30min til server restart 15 etc, but in the end nothing happens. the mission is still running. 
-we put this in the server.cfg:  serverCommandPassword = "PW"
-and this into the mypass.hpp:  "PW" (datapath of the .hpp= \userconfig\restart\myPass.hpp)
-in the script there is "#restart" as the server command. what might have gone wrong?

**Comment by k4s0** [comment]
@madpat3 send me an email (see my github profile page )
